name: Web extension Continuos Integration

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  build_production_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: echo It's All Good Here!
