name: Web extension Continuos Integration

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  Build_Production:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Build with yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 16.x
      - run: yarn build-prod

